### ISSUE TITLE
RuntimeZipTask Doesn't Consistently Produce Target Distributions

### ISSUE THREAD

**Issue by DSheirer** [beryx/badass-runtime-plugin#1]
With plugin version 1.1.0,  I can't get the runtimeZip task to consistently run and produce cross-platform zip distributions.  Each time I run a 'clean' with 'runtimeZip', gradle detects that runtimeZip is 'UP-TO-DATE' and completely skips zipping the target distributions.  The target distribution files are being generated correctly for each target distribution, they're just not being zipped up.

It seems to work the first time that I run the 'runtimeZip' task, but I can't get it too work consistently each time.

Here's my runtime task definition:

runtime {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    modules = ['java.desktop', 'java.naming', 'jdk.unsupported', 'jdk.unsupported.desktop']
    imageZip = file("$buildDir/app-name-" + version + ".zip")

    targetPlatform('linux-x64', '/media/denny/WD250GB/java/linux/jdk-11.0.1')
    targetPlatform('osx-x64', '/media/denny/WD250GB/java/osx/jdk-11.0.1.jdk')
    targetPlatform('windows-x64', '/media/denny/WD250GB/java/windows/jdk-11.0.1')
}

**Comment by siordache** [comment]
There were a couple of task parameter with incorrect annotations. I just published the patch release 1.1.1. Can you please check if this version fixes the problem?

**Comment by DSheirer** [comment]
Yes, this fixes the problem.  Thank you very much for the quick fix!
