### ISSUE TITLE
Incorrect launch script used when shadow plugin is present

### ISSUE THREAD

**Issue by shollander** [beryx/badass-runtime-plugin#10]
Normally, the runtime plugin will use its own launch script template which will use the jre bundled within the runtime image instead of the installed version of java or `JAVA_HOME`.

When using the runtime plugin together with the shadow plugin, this does not work correctly. The launch script that ends up getting used is the default one supplied by the application plugin which tries to use `JAVA_HOME` or the path.

I am using `org.beryx.runtime` version `1.1.5` and `com.github.johnrengelman.shadow` version `4.0.4`

**Comment by siordache** [comment]
@shollander Thanks for reporting this problem. Fixed in release 1.1.6.
