### ISSUE TITLE
help : gradlew jpackage need icon 

### ISSUE THREAD

**Issue by sosoeo** [beryx/badass-runtime-plugin#109]
this plugin is so wonderful!!! 👍， 
but today a little trouble face me for long time,
how can I add icon file for msi installer ?  I have tryed  'org.beryx.jlink' , that works when use gradle jpackage and give a icon option settings like :
	jpackage {
		jpackageHome = 'C:/jdk-17.0.0-zulu'
		outputDir = 'my-packaging'
		// imageOutputDir = file("$buildDir/my-packaging-image")
		// installerOutputDir = file("$buildDir/my-packaging-installer")
		imageName     = "flatSwingDemo"             
		appVersion    = "1.0.0"
		**icon = file("$projectDir/favicon.ico")**
		skipInstaller = false
		installerName = "myInstaller"            
		installerType = 'msi'
		installerOptions = ['--win-menu', '--win-shortcut','--win-dir-chooser']
	}

**but when I switched to     id 'org.beryx.runtime' version '1.12.7',  the idea said 'icon' is unknown property  unitll I removed it.**

can you add icon back for  this plugin too?

**Comment by canglongxiang** [comment]
Try this configuration:

```
runtime {
    jpackage {
        imageOptions = [
                '--icon', '$projectDir/favicon.ico'
        ]
    }
}
```

**Comment by hakanai** [comment]
The sample project does it the same way.

https://github.com/beryx-gist/badass-runtime-example-javafx/blob/master/build.gradle#L54

I tested the sample earlier today and the icon seemed to be present, so I'll close this as it's pretty well documented by being in the sample project.

Having some convenience for setting the icon without using flags would be nice, but the same goes for all the other flags.
