### ISSUE TITLE
Keep original distZip behavior

### ISSUE THREAD

**Issue by joeha480** [beryx/badass-runtime-plugin#12]
Would it be possible to keep the distZip behavior from the application plugin while using this plugin? I would like to be able to build without runtime as before and with the embedded runtime as well.

**Comment by siordache** [comment]
@joeha480  I fixed the distZip behavior in release 1.1.7. Give it a try!

**Comment by joeha480** [comment]
@siordache Awesome! It works great. Thanks a lot!
