### ISSUE TITLE
jpackageImage fails because the `--input` is incorrect

### ISSUE THREAD

**Issue by gotson** [beryx/badass-runtime-plugin#120]
when i run `jpackageImage` i get the following error:

```
Starting process 'command '/.../.sdkman/candidates/java/17.0.0-tem/bin/jpackage''. Working directory: /.../Development/komga/komga Command: /.../.sdkman/candidates/java/17.0.0-tem/bin/jpackage --type app-image --input /.../Development/komga/komga/build/libs/lib --main-jar komga-0.146.0-plain.jar --main-class org.gotson.komga.ApplicationKt --dest /.../Development/komga/komga/build/jpackage --name komga --app-version 0.146.0 --runtime-image /.../Development/komga/komga/build/jre
Successfully started process 'command '/.../.sdkman/candidates/java/17.0.0-tem/bin/jpackage''
Bundler Mac Application Image skipped because of a configuration problem: The configured main jar does not exist komga-0.146.0-plain.jar in the input directory 
Advice to fix: The main jar must be specified relative to the input directory (not an absolute path), and must exist within that directory
```

Seems like the problem is here: `--input /.../Development/komga/komga/build/libs/lib`. There is no such directory.

Seems there is a hardcoded `lib` [here](https://github.com/beryx/badass-runtime-plugin/blob/021a2183555223ba2fd16d8a9606cf769e30e882/src/main/groovy/org/beryx/runtime/impl/JPackageImageTaskImpl.groovy#L73).

I have no idea why though.

**Comment by hakanai** [comment]
In another test I was investigating, I found the input being specified as:

> --input /path/to/project/build/install/Full app name/lib

Yours had "build/libs/lib" - this one has "build/install/Full app name/lib" - so this may have been fixed since whatever version you're running there.
