### ISSUE TITLE
Spaces in Installation/Execute Path Cause Windows Launcher to Fail 

### ISSUE THREAD

**Issue by DSheirer** [beryx/badass-runtime-plugin#2]
When the packaged runtime zip file is extracted into a directory/path that contains spaces, the windows launch script fails.

--------------------------------------------------------------
Below is feedback from a user of my application (sdr-trunk) that was built/zipped using the runtimeZip target:

Tried to run sdr-trunk.bat and get.

C:\Users\Me\Desktop\Radio & Phone\SDR\sdr-trunk-0.4.0-alpha.7-windows-x64\sdr-trunk-windows-x64\bin>sdr-trunk
'Phone\SDR\sdr-trunk-0.4.0-alpha.7-windows-x64\sdr-trunk-windows-x64\bin' is not recognized as an internal or external command,
operable program or batch file.
'Phone\SDR\sdr-trunk-0.4.0-alpha.7-windows-x64\sdr-trunk-windows-x64\bin..' is not recognized as an internal or external command,
operable program or batch file.

ERROR: JAVA_HOME is set to an invalid directory: C:\Users\Me\Desktop\Radio

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

If i copy it to another folder where there are no spaces everything runs fine. for eg. c:\Users\Me\sdrtrunk

**Comment by siordache** [comment]
@DSheirer Fixed in 1.1.2. The real culprit was the ampersand.

**Comment by DSheirer** [comment]
@siordache Thanks again for the quick fixes!  cheers, Denny
