### ISSUE TITLE
No windows start menu entry

### ISSUE THREAD

**Issue by ChrisLMerrill** [beryx/badass-runtime-plugin#25]
I'm moving from another gradle plugin using the old jpackager...so I was very happy to find this one! This may be more of a question than an issue. Is there a better place for me to ask?

My installer works and runs my app, but no start-menu item is created in Windows. I included "--win-menu" in the runtime.jpackage.installerOptions array. I double-checked the jpackage command emitted during the build, and found that it does have the --win-menu parameter, so I hit up the core-java dev list.

A dev pointed out this message in my build output.
  "Multiple launchers found in predefined app-image. jvm will be used as primary launcher."
and he questioned this jpackage parameter:
  --input MyProject\build\image\lib
wondering why we would use the JRE image lib folder?  Instead of a target app folder, such as MyProject\build\install\MyApp\lib? I am too much of a newbie with this stuff to give him a good answer.

Then, in the MyProject\build\jpackage\MyApp\app folder, the jvm.cfg file appears because of the above issue. They are expecting MyApp.cfg to be there. It was also, but they were picking up the jvm.cfg file instead. They've opened a bug to correct that part of the problem:
  https://bugs.openjdk.java.net/browse/JDK-8230920
So they think that is why I have no start menu item. 

But I'm guessing others have been able to build a Windows installer that creates a Start menu item using this gradle plugin...so I'm wondering if I have configured something wrong. Does this look correct?

```
runtime {
    options = ['--strip-debug', '--no-header-files', '--no-man-pages']
    modules = [... long list ...]
    jpackage {
        installerType = nativeType
        jpackageHome = 'C:\\Apps\\OpenJDKs\\jdk-14'
        installerOptions = ["--win-per-user-install", "--win-menu", "--app-version", version, "--name", project.name]
    }
}
```

My goal is a native installer for the app. Windows, in this case...but eventually Mac and Linux. I'm close. The 3 things I'm missing are:

1. start menu item
2. custom icon
3. launch the app after install

TIA!
Chris

**Comment by siordache** [comment]
1. I cannot reproduce the problem. I also get the error:
`"Multiple launchers found in predefined app-image. jvm will be used as primary launcher.`
but the start-menu is created. 
Try again using also the `--win-menu-group` option.

2. It seems that the `--icon`option is not supported on Windows:
`Option [--icon] is not valid with package-type [msi].`

3. I think that currently jpackage cannot launch the app after install.

**Comment by ChrisLMerrill** [comment]
Thanks for that. It seems like I won't be able to achieve my requirement for the installer at this time, so I'll use this plugin and jpackage to create the app image and run InnoSetup directly, instead.

**Comment by ChrisLMerrill** [comment]
FWIW, I found that:
        imageOptions = ["--icon", "package/windows/MuseIDE.ico"]
Works for getting the correct icon onto the executable in the application image.

As a result, I get the correct icon on the installer that I produce using InnoSetup directly. However, the installers (msi, exe) produced by jpackage still don't create the windows menu item for me :(

**Comment by DJViking** [comment]
I just want to mention that InnoSetup has been removed from jpackage. You would need to use WiX to create a Windows installer for either MSI or EXE.
