### ISSUE TITLE
jlinkZip task not executing

### ISSUE THREAD

**Issue by joeo73** [beryx/badass-runtime-plugin#3]
Reproduce:
gradle clean jlinkZip
gradle clean
gradle clean jlinkZip <-- Does not produce new zip file.

gradle --version

------------------------------------------------------------
Gradle 5.1.1
------------------------------------------------------------

Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807

Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.1 (AdoptOpenJDK 11.0.1+13)
OS:           Mac OS X 10.13.6 x86_64

**Comment by joeo73** [comment]
This gets past the issue for me
gradle --rerun-tasks jlinkZip --info

**Comment by siordache** [comment]
Is this a badass-runtime-plugin or a badass-jlink-plugin issue? 

Which version of the plugin do you use?

**Comment by joeo73** [comment]
org.beryx.jlink, 2.4.1

**Comment by siordache** [comment]
Please try it with badass-jlink 2.4.3.

I'm closing this issue now, because it has nothing to do with the `badass-runtime` plugin.
If the problem stil occurs, please open a ticket for the `badass-jlink` plugin and also post the output of:
`./gradlew -is clean jlinkZip`
