### ISSUE TITLE
Duplicate data in runtime image and application image

### ISSUE THREAD

**Issue by DJViking** [beryx/badass-runtime-plugin#33]
There is duplicate data in both the application image and the runtime image after running the jpackageImage task.

The runtime image created by jlink in the jre task and the application distribution created by the installDist task are both copied into the image directory by the RuntimeTask.

Because this runtime image is supplied to both --input and --runtime-image of jpackage, the content of its lib directory is duplicated in the application image created by jpackageImage task.
```
build/jpackage/imageName/app
build/jpackage/imageName/runtime/lib
```

You don't need the output of RuntimeTask in JPackageImageTask. All you need is the jreDir and distDir. It should depend on these two tasks, same task dependencies as the RuntimeTask has.
```
'--input', "$td.distDir${File.separator}lib",
'--runtime-image', td.jreDir,
```

**Comment by siordache** [comment]
@DJViking Thanks for the PR! Release 1.6.0 contains your fix.
