### ISSUE TITLE
Fix jpackage after changes in 14-jpackage+1-49

### ISSUE THREAD

**Issue by DJViking** [beryx/badass-runtime-plugin#37]
The next EA build of JPackage is available at https://jdk.java.net/jpackage/

Build 14-jpackage+1-49 (2019/10/2) contains the following changes (since
Build Build 14-jpackage+1-33 on 2019/08/19)

List of changes https://mail.openjdk.java.net/pipermail/core-libs-dev/2019-October/062682.html

**Comment by DJViking** [comment]
I will look over these changes and update the jpackage tasks accordingly.

**Comment by siordache** [comment]
Thanks! Can you please also review and merge [this PR](https://github.com/beryx/badass-jlink-plugin/pull/91)?
