### ISSUE TITLE
Invalid dependency causing NPE

### ISSUE THREAD

**Issue by chrisrush1** [beryx/badass-runtime-plugin#41]
I was having an issue using suggestModules on my main project, no problems on a simple test. 
I posted on StackOverflow and Jose Pereda replied with a good workaround but pointed out there was an issue with the runtime plugin when a plugin fails to find a valid artifact because it returns a zip file instead of a jar file. 
Jose's suggestion was maybe to 
'A quick fix in Utils:getArtifact like:

`artifact != null ? artifact.file : null`'

Here's a link to his full answer and my question to give some more context:

https://stackoverflow.com/questions/58524790/badass-runtime-suggestmodules-npe-problem/58528351#58528351

 Thanks for the great plugins, they're massivey helpful.

**Comment by siordache** [comment]
@chrisrush1 Thanks for reporting!
@jperedadnr Thanks for analyzing this issue!

Fixed in 1.7.1. The plugin will also issue a warning if the dependency is invalid.
