### ISSUE TITLE
Duplicate/Triplicate dlls?

### ISSUE THREAD

**Issue by chrisrush1** [beryx/badass-runtime-plugin#42]
Hi,

Thanks for the quick fix on the NPE issue. :)

Here's a link to the SO issue for the NPE issue that also contains my build.gradle file

https://stackoverflow.com/questions/58524790/badass-runtime-suggestmodules-npe-problem/58528351#58528351

Here's my build.gradle, I've used this on a very simple test application and I observed the same duplication/triplication of dlls.

`plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.8'
    id 'org.beryx.runtime' version '1.7.0'
    id "com.github.johnrengelman.shadow" version "5.1.0"
    id 'idea'
}

repositories {
    mavenCentral()
}
sourceCompatibility = 11
targetCompatibility = 11

def java_home14= System.getenv('JAVA_HOME_14')
def appVersion = "1.0"

dependencies {
}

javafx {
    version = "13"
    modules = ['javafx.base', 'javafx.controls', 'javafx.fxml']
}

def jvmArgsList = ['--add-opens', 'javafx.controls/javafx.scene.control.skin=ALL-UNNAMED']

application {
    mainClassName = 'org.openjfx.Launcher'
    applicationDefaultJvmArgs = jvmArgsList
}

runtime {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    modules = [
            'java.logging',
            'java.xml',
            'java.desktop',
            'jdk.unsupported',
            'jdk.unsupported.desktop',
            'java.datatransfer',
            'jdk.jfr',
            'java.scripting']

    jpackage {
        if (java_home14 == null) {
            throw new RuntimeException("java_home14 is not defined.")
        }
        jpackageHome = java_home14
        resourceDir =file("$buildDir/resources")
        if(org.gradle.internal.os.OperatingSystem.current().windows) {
            installerType = 'exe'
            imageName= 'TableFX'
            installerName= 'TableFX'
            jvmArgs=jvmArgsList
            appVersion=appVersion
            installerOptions = ['--win-dir-chooser', '--win-menu', '--win-shortcut']

        }
    }
}

`

I've noticed there are duplicate and triplicate dlls in the windows installed folder for my application.
I've tried moving them to see what's needed. 
In the root of the application folder there are dlls and then the same dlls reside under [root]\runtime\bin. Most of these dlls are also in the jar file found under [root]\app, although not all. 
I've moved all the dlls from the root folder and runtime\bin into another folder and my application seems to run ok. 
Obviously I'm keen to make the installer as small as possible so could you let me know how it's possible to avoid the duplication if it's not a bug?

Thanks

**Comment by siordache** [comment]
It's probably a [jpackage bug](https://bugs.openjdk.java.net/browse/JDK-8230863).

**Comment by chrisrush1** [comment]
Ah yes so it is. Thanks for linking me to that.
