### ISSUE TITLE
Add/Remove programs entries

### ISSUE THREAD

**Issue by chrisrush1** [beryx/badass-runtime-plugin#43]
When installing the installer made with jpackage is there an option to overwrite a previous install of this program? At present I end up with multiple installs if I don't explicitly uninstall the previous version first.

Kind Regards

**Comment by siordache** [comment]
For Windows you can use the `--win-upgrade-uuid` option:
```
jlink {
    ...
    jpackage {
        if (org.gradle.internal.os.OperatingSystem.current().windows) {
            installerOptions = [
                '--win-upgrade-uuid', 'aabbccdd-eeff-1122-3344-556677889900',
                ...
            ]
        }
    }
}
```
