### ISSUE TITLE
How to specify an application icon?

### ISSUE THREAD

**Issue by byron-dm** [beryx/badass-runtime-plugin#45]
There used to be an "--icon" switch. Has it been removed from recent jpackage builds?

**Comment by siordache** [comment]
It's strange that the `--icon` option is no longer mentioned on the [JEP 343 page](https://openjdk.java.net/jeps/343). 
However, `jpackage --help` still displays it (with build 14-jpackage+1-70):

```
Options for creating the application image:
  --icon <icon file path>
          Path of the icon of the application package
          (absolute path or relative to the current directory)
```


You should be able to configure an icon for your application with the following code:

```
jpackage {
    imageOptions = ['--icon', 'src/main/resources/java.ico']
    ...
}
```

**Comment by Parth** [comment]
Yep here is how I do it: https://github.com/lockbook/lockbook-dev-desktop/blob/master/build.gradle#L35
