### ISSUE TITLE
Generated Windows Launch Script Path Length Can Exceed Maximum

### ISSUE THREAD

**Issue by DSheirer** [beryx/badass-runtime-plugin#5]
The generated windows launch script can exceed the maximum command line length due to explicitly listing each of the jar libraries on the classpath.  Can you use wildcarding to abbreviate this list?

----------------------------
As reported by a user of my github project (sdr-trunk),

The set CLASSPATH command exceeds the maximum character length limit of a .bat command line, which is 8191.

In my case, the length of my CLASSPATH has become 8223. 

As a temporary solution, I moved the sdrtrunk directory to the root of C:/. That works but leaves little possibilities to add just a few more variables.

For the Windows environment, can the CLASSPATH be reviewed/optimized and eliminate unnecessary variables? (I noticed approx 10 variables with the abbreviation 'LINUX'... are these really used?)
 
Below is my CLASSPATH value (8223 characters) from the .bat command line.

C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin>set CLASSPATH="C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\sdr-trunk-0.4.0-alpha.8.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\commons-math3-3.6.1.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\java-lame-3.98.4.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\jmbe-interface-0.3.3.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\libresample4j-0.1.3.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\radioreference-14.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\wsdl4j-1.5.1.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\logback-classic-1.2.3.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\logback-core-1.2.3.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\jackson-dataformat-xml-2.9.8.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\jiconfont-font_awesome-4.7.0.1.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\jiconfont-javafx-1.0.0.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\jiconfont-swing-1.0.1.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\JTransforms-3.1.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\guava-27.0.1-jre.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\jide-oss-3.6.18.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\miglayout-swing-5.2.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\usb4java-javax-1.3.0.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\usb-api-1.0.2.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\tablefilter-swing-5.4.0.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\axis-1.4.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\axis-jaxrpc-1.4.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\usb4java-1.3.0.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\commons-lang3-3.8.1.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\mina-http-2.0.19.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\mina-core-2.0.19.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\javafx-controls-11.0.1-win.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\javafx-controls-11.0.1-linux.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\javafx-controls-11.0.1-mac.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\javafx-swing-11.0.1-win.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\javafx-swing-11.0.1-linux.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\javafx-swing-11.0.1-mac.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\javafx-graphics-11.0.1-win.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\javafx-graphics-11.0.1-linux.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\javafx-graphics-11.0.1-mac.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\javafx-graphics-11.0.1.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\javafx-base-11.0.1-win.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\javafx-base-11.0.1-linux.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\javafx-base-11.0.1-mac.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\javafx-base-11.0.1.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\slf4j-api-1.7.25.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\libusb4java-1.3.0-linux-x86.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\libusb4java-1.3.0-linux-x86-64.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\libusb4java-1.3.0-win32-x86.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\libusb4java-1.3.0-win32-x86-64.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\libusb4java-1.3.0-darwin-x86-64.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\libusb4java-1.3.0-linux-arm.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\libusb4java-1.3.0-linux-aarch64.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\JLargeArrays-1.6.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\jackson-module-jaxb-annotations-2.9.8.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\jackson-databind-2.9.8.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\jackson-core-2.9.8.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\jackson-annotations-2.9.0.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\woodstox-core-5.0.3.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\stax2-api-3.1.4.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\jiconfont-1.0.0.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\commons-math3-3.5.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\failureaccess-1.0.1.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\jsr305-3.0.2.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\checker-qual-2.5.2.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\error_prone_annotations-2.2.0.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\j2objc-annotations-1.1.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\animal-sniffer-annotations-1.17.jar;"C:\Users\quietpc\Downloads\sdr-trunk-0.4.0-alpha.8-windows-x64\sdr-trunk-windows-x64\bin\"..\lib\miglayout-core-5.2.jar;

**Comment by DSheirer** [comment]
@siordache Thanks for the patch.

Does this plugin automatically pull in the platform-specific openjfx dependencies for each platform-specific build, or am I doing something wrong?  When I remove the openjfx platform dependencies in the gradle build, they do not get included in the runtimeZip products.

The only way that I've found to get the platform-specific openjfx dependencies is to explicitly list them in the gradle dependencies block.  I'd prefer to only include the minimum dependencies in each runtimeZip product.

Thanks for any help you can provide?

Denny

**Comment by siordache** [comment]
The badass-runtime plugin has no special support for openjfx. This is offered by the `org.openjfx.javafxplugin`, but it doesn't deal with multiple target platforms. If you remove the openjfx platform dependencies from your build script, the `org.openjfx.javafxplugin` will pull only the openjfx dependencies for the platform on which your build runs. Therefore,  you need to keep all openjfx dependencies in your build script.

One way to include only the minimum dependencies in each runtimeZip product is to remove the unnecessary openjfx dependencies before the start of the zip operation.
Try adding this to your build.gradle: 

```
tasks.runtimeZip.doFirst {
    delete(fileTree('build/image/sdr-trunk-linux-aarm64/lib').include { it.name ==~ /javafx.*-(win|mac)\.jar/ })
    delete(fileTree('build/image/sdr-trunk-linux-x64/lib').include { it.name ==~ /javafx.*-(win|mac)\.jar/ })
    delete(fileTree('build/image/sdr-trunk-osx-x64/lib').include { it.name ==~ /javafx.*-(win|linux)\.jar/ })
    delete(fileTree('build/image/sdr-trunk-windows-x64/lib').include { it.name ==~ /javafx.*-(linux|mac)\.jar/ })
}
```

**Comment by DSheirer** [comment]
Perfect!  You just shaved 10MB+ off of each of my images.  Thanks again.
