### ISSUE TITLE
Example of plugin use with spring boot project

### ISSUE THREAD

**Issue by jdegeete** [beryx/badass-runtime-plugin#50]
I am trying to use the plugin on a toy spring boot problem (for later use in a real project) but I cannot get it to work. Or, as I suspect, it does work but I have an imperfect understanding of how the end result works.

I started from a [trivial spring boot demo project that was already using the plugin](https://github.com/eyals24/my-demo/tree/5bcbac39472facacf18f2212ce8aeff8332b657e]).

I only updated some of the plugin versions and source compatibility (as well as the gradle wrapper provided with the project):

```
buildscript {
	ext {
		springBootVersion = '2.2.4.RELEASE'
	}
	repositories {
		mavenCentral()
	}
}

plugins {
	id 'java'
	id 'org.beryx.runtime' version '1.8.0'
	id 'org.springframework.boot' version '2.2.4.RELEASE'
}

apply plugin: 'io.spring.dependency-management'

group = 'com.testjlink'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 13
targetCompatibility = 13

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

mainClassName = 'com.testjlink.demo.DemoApplication'

runtime {
	options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
	modules = ['java.management', 'java.naming', 'java.instrument', 'java.sql', 'jdk.unsupported', 'jdk.security.jgss', 'java.desktop']
}

tasks.runtime.doLast {
	copy {
		from('src/main/resources')
		into("$buildDir/image/bin")
	}
}
```

Without any issues, I am able to execute `gradlew clean build runtime` and see the result.

After navigating to the generated folder `build\image\bin` I execute the `demo.bat` file (for Windows but the same holds with the provided unix/mac demo start script). This returns the following error:
```
Error: Could not find or load main class com.testjlink.demo.DemoApplication
Caused by: java.lang.ClassNotFoundException: com.testjlink.demo.DemoApplication
```

I altered the bat file to get a peek at the executed command and get the following: 
```
"C:\Users\Jeroen\Documents\Oehoe\my-demo\build\image\bin\../bin/java.exe"     -classpath "C:\Users\Jeroen\Documents\Oehoe\my-demo\build\image\bin\../lib/*" com.testjlink.demo.DemoApplication
```
I can confirm that the demo-0.0.1-SNAPSHOT.jar is present, as added to the classpath,  in the `image\lib` folder.

Do I need to change the runtime block of the gradle file to get it to work or is there something else at play?

**Comment by siordache** [comment]
Currently, the plugin has no built-in support for Spring. The workaround is to replace the line
```
mainClassName = 'com.testjlink.demo.DemoApplication'
```

with

```
startScripts.mainClassName = 'org.springframework.boot.loader.JarLauncher'
```

in your build.gradle.

**Comment by jdegeete** [comment]
That indeed solved the problem... But I ran into some new (related) problems.

The following code works when I do a simple `gradlew clean build runtime`. 

```
javafx {
    version = '14'
    modules = ['javafx.controls', 'javafx.graphics', 'javafx.fxml']
}

startScripts.mainClassName = 'org.springframework.boot.loader.JarLauncher'

runtime {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    modules = ['java.management', 'java.naming', 'java.instrument', 'java.sql', 'jdk.unsupported', 'jdk.security.jgss',
               'java.desktop', 'java.logging', 'jdk.jfr', 'java.xml', 'java.scripting']
    jpackage {
        jpackageHome = '/Program Files/Java/jdk-14/'
        if(org.gradle.internal.os.OperatingSystem.current().windows) {
            installerType = 'msi'
            installerOptions = ['--win-per-user-install', '--win-dir-chooser', '--win-menu', '--win-shortcut']
        }
    }
}
```

However,  `gradlew clean build jpackage` throws me an error related to:

```
Caused by: java.lang.NullPointerException
        at org.beryx.runtime.data.JPackageData.getDefaultMainClass(JPackageData.groovy:111)
```

I figured I needed to add an additional line to my code:

```
startScripts.mainClassName = 'org.springframework.boot.loader.JarLauncher'
mainClassName = 'org.springframework.boot.loader.JarLauncher'             
```

After that `gradlew clean build jpackage` runs without any complaints but nothing seems to work anymore. I cannot run the generated jar file.

When I first run `gradlew clean build` using only `startScripts.mainClassName = 'org.springframework.boot.loader.JarLauncher'` and then add the additional line `mainClassName = 'org.springframework.boot.loader.JarLauncher'` before running `gradlew jpackage` everything works as it should. But that kind off defeats the purpose of having an automated build tool.

Is there a workaround to this?

**Comment by tsing** [comment]
Another way to use with spring boot is using something like below, which does require changing mainClassName. 

```

tasks.withType<org.springframework.boot.gradle.tasks.bundling.BootJar> {
    enabled = false
}

tasks.withType<Jar> {
    enabled = true
}
```

**Comment by jdegeete** [comment]
@tsing Could you elaborate a bit? I am ensure how this works.

**Comment by siordache** [comment]
@jdegeete Try this:
```
mainClassName = 'com.testjlink.demo.DemoApplication'
startScripts.mainClassName = 'org.springframework.boot.loader.JarLauncher'

runtime {
    ....
    jpackage {
        mainClass = 'org.springframework.boot.loader.JarLauncher'
        ....
    }
}
```

**Comment by jdegeete** [comment]
@siordache That did the trick! Thanks.
