### ISSUE TITLE
installerOutputDir option errors out

### ISSUE THREAD

**Issue by JamzTheMan** [beryx/badass-runtime-plugin#53]
Using the option `installerOutputDir = file("releases")` fails execution with the following error:

```Could not get unknown property 'FileUtils' for object of type org.gradle.process.internal.DefaultExecAction_Decorated.```

FWIW I also get this using org.beryx.jlink in another project as well so both plugins have the issue.

**Comment by siordache** [comment]
I'm not able to reproduce it. Which Gradle version, which JDK, and which plugin version do you use?

**Comment by siordache** [comment]
OK, I was able to reproduce the issue. It's fixed in 1.8.2.
