### ISSUE TITLE
Unable to set default JVM args

### ISSUE THREAD

**Issue by JamzTheMan** [beryx/badass-runtime-plugin#55]
jpackage fails if I add a launcer {} block under runtime {}

launcher {
        jvmArgs = ["-Xss8M"]
}

Error message just points to my runtime{} block

```Build file 'C:\Users\Jamz\Development\git\JamzTheMan\MapTool\build.gradle' line: 118

A problem occurred evaluating root project 'MapTool'.
> No signature of method: build_2kszlb0cx3ow1bo7yiha2n6s4.runtime() is applicable for argument types: (build_2kszlb0cx3ow1bo7yiha2n6s4$_run_closure6) values: [build_2kszlb0cx3ow1bo7yiha2n6s4$_run_closure6@49539951]
  Possible solutions: run(), run()
```

Windows 10, JDK 14, Gradle 6.3

UPDATE: It seems to work if I put the `jvmArgs` in the `jpackage` block so if that's intended it's maybe just a documentation issue. FYI using latest docs shows:

**jvmArgs**
list of JVM arguments to be passed to the virtual machine. 
*defaultValue:* the jvmArgs value configured in the launcher block or an empty list```

**Comment by DJViking** [comment]
There is no launcher argument for Badass Runtime Plugin. There is though for Badass JLink Plugin.

Place the jvmArgs directly under jpackage block.
```
runtime {
    jpackage {
        jvmArgs = [ "-Xss8M" ]
    }
}

**Comment by siordache** [comment]
Copy and paste error. I updated the documentation.

**Comment by JamzTheMan** [comment]
great, thanks!  Great plugins btw, really appreciate it. It's making our lives much easier!

**Comment by siordache** [comment]
Thanks, @JamzTheMan !
