### ISSUE TITLE
Easier cross-platform building: targetPlatform with URI to JRE

### ISSUE THREAD

**Issue by ari** [beryx/badass-runtime-plugin#59]
targetPlatform currently requires a path to the JRE already somewhere on disk. It would be great if we could provide co-ordinates to a maven repo, or even a simple helper for adoptopenJDK to grab the appropriate artifacts, unpack them and use them.

**Comment by siordache** [comment]
In 1.10.0, I added the `jdkDownload` method, which downloads and unpacks a JDK distribution from a given URL.

Usage example:
```
runtime {
    ...
    targetPlatform('linux') {
        jdkHome = jdkDownload("https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.1%2B7/OpenJDK14U-jdk_x64_linux_hotspot_14.0.1_7.tar.gz")
    }
```

See [the documentation](https://badass-runtime-plugin.beryx.org/releases/latest/#_methods) for details and more advanced usages.

**Comment by ari** [comment]
Wow, thanks so much. That's really brilliant.
