### ISSUE TITLE
Is there a way to include/enable AppCDS

### ISSUE THREAD

**Issue by batraz90** [beryx/badass-runtime-plugin#60]
I'm interested in improving the start-up time of my applications and stumbled uponn Application Class Data Sharing but I already failed by trying to add `-XX:ArchiveClassesAtExit=${ARCHIVE};` to my JVM arguments. The JVM will not start and produce the following error message:
```
Error occurred during initialization of VM
DynamicDumpSharedSpaces is unsupported when base CDS archive is not loaded

```
Any ideas why it's not working and how to enable App-CDS with jlink/runtime images?

**Comment by siordache** [comment]
I put up [this example project](https://github.com/beryx-gist/badass-runtime-example-javafx-cds), which configures the runtime image to use CDS.

The following three steps are needed:

1. Create a JDK-CDS-archive using `-Xshare:dump`. This step can be automated by [providing a `doLast` closure for the runtime task](https://github.com/beryx-gist/badass-runtime-example-javafx-cds/blob/0ef0cdae551370a439c178f5962a296179f357df/build.gradle#L31-L37).
2. When running the application for the first time, use `-XX:ArchiveClassesAtExit` to create the App-CDS-archive.
3. Subsequent runs should use `-XX:SharedArchiveFile`.

Steps 2 and 3 can be automated by providing custom start templates for [Unix-like](https://github.com/beryx-gist/badass-runtime-example-javafx-cds/blob/aabe0282ec7dea04507b12d33b24fd80ed251f23/templates/unixScriptTemplate.txt#L33-L38) and [Windows platforms](https://github.com/beryx-gist/badass-runtime-example-javafx-cds/blob/aabe0282ec7dea04507b12d33b24fd80ed251f23/templates/windowsScriptTemplate.txt#L20-L22).

**Comment by batraz90** [comment]
Awesome. It works!
