### ISSUE TITLE
applicationDefaultJvmArgs ignored

### ISSUE THREAD

**Issue by micheljung** [beryx/badass-runtime-plugin#61]
According to [the documentation](https://badass-runtime-plugin.beryx.org/releases/latest/):

> jvmArgs
>  list of JVM arguments to be passed to the virtual machine.
>  defaultValue: the arguments configured in the applicationDefaultJvmArgs property of the application extension

However, as can be seen in https://github.com/micheljung/badass-runtime-example/commit/b247865b66a3781d974c5c1462ab4f73460ec38f, specifying `applicationDefaultJvmArgs` instead of `jvmArgs` does not pass arguments to the VM.

**Comment by siordache** [comment]
Fixed in 1.11.1
