### ISSUE TITLE
Application launch without cmd on Windows

### ISSUE THREAD

**Issue by vadimpikha** [beryx/badass-runtime-plugin#63]
Currently app starts with associated console. I would like to have an option for launching without that. I have tried to change .bat script template to use **javaw.exe** instead of **java.exe**. It had effect (I was able to close console and continue using my application) but I would like to console not appear at all. Please add this option to plugin or help me with working template. Thanks :)

**Comment by siordache** [comment]
In 1.11.2 you can set `noConsole=true` in the `launcher` block:
```
runtime {
    ...
    launcher {
        noConsole = true
    }
}
```

**Comment by vadimpikha** [comment]
It works with executing task `"runtime"` and launching `"myApp.bat"`. But executing `"jpackageImage"` and launching "myApp.exe" doesnt have same result. It still has console. Maybe I am doing something wrong?

**Comment by siordache** [comment]
The `noConsole` property has no effect on the `jpackage` and `jpackageImage` tasks. By default, the executables produced by these tasks have no console. The console is displayed only if you explicitly configure the `--win-console` option:

```
runtime {
    ...
    jpackage {
        if(org.gradle.internal.os.OperatingSystem.current().windows) {
            ...
            imageOptions = ['--win-console']  // Remove this line if you don't want a console
        }
    }
}
```

Clone the [badass-runtime-example-javafx project](https://github.com/beryx-gist/badass-runtime-example-javafx) and execute `gradlew jpackageImage`. No console should appear when executing `hellofx.exe`. However, if a console is displayed on your machine, please post your exact configuration (Windows version, JDK distribution etc.).

If badass-runtime-example-javafx behaves as expected but your application still displays a console, try to put up an example project that allows reproducing this issue.

**Comment by vadimpikha** [comment]
Yeah, I realized than I copy-pasted code with `--win-console`. I removed that and now works as expected. Thanks a lot for help
