### ISSUE TITLE
Jpackage addition data files

### ISSUE THREAD

**Issue by TimMcGilly** [beryx/badass-runtime-plugin#65]
In my runtime image I have a load of separate data files which are required for the program to run. In the runtime they are copied correctly from the install dir generated by install installDist.

However in the jpackage it only includes the jar files and not of the non jar files from installDist or the runtime. 

https://docs.oracle.com/en/java/javase/14/jpackage/image-and-runtime-modifications.html

This help article on jpackage suggest that for this you could copy the files into the jpackage image before the finial installer generation. Is this the best method to do this? 

If so how would you recommending copying the data files into the jpackage folder after the jpackageImage task. I've considered using copy taks with MustRunAfter jpackageImage and Jpackage depends on copy task but not certain whether there is a better way to do this or upto date checker issue due to multiple tasks writing to same output?

**Comment by siordache** [comment]
You can configure a `doLast` action for the `jpackageImage` task. For example:

```
tasks.jpackageImage.doLast {
    copy {
        from "src/main/resources"
        include "splash.png"
        into "build/jpackage/$project.name/app"
    }
}
```

In most cases, copying the data files after executing the `runtime` task will also do the trick:

```
tasks.runtime.doLast {
    copy {
        from "src/main/resources"
        include "splash.png"
        into "$buildDir/image/bin"
    }
}
```

Choose the method that works best for you.

**Comment by TimMcGilly** [comment]
Thank you, I've got that working with my project.
