### ISSUE TITLE
executableDir = "" in windows startscript wrong JAVA_HOME

### ISSUE THREAD

**Issue by TimMcGilly** [beryx/badass-runtime-plugin#67]
In the application block I have
```
application{
    executableDir = ""
}
```
to have the startscript in the main dir of the image.

However the .bat file end up with the wrong java home of `set JAVA_HOME="%~dp0.."` which is one directory too high. If I modify the bat file to `set JAVA_HOME="%~dp0"` removing the `..` it find the java image correctly and launches.

**Comment by TimMcGilly** [comment]
After doing more research this appear to be a bug in gradle and not this plugin. https://github.com/gradle/gradle/issues/10387

Workaround:
```
startScripts{
    doLast {
        windowsScript.text =
                windowsScript.text
                .replace("set JAVA_HOME=\"%~dp0..\"", "set JAVA_HOME=\"%~dp0\"")
    }
}
```

Should I close this as it is a issue in gradle not the plugin or leave it open for people encountering issue until fixed in gradle?

**Comment by siordache** [comment]
Thanks for analyzing this issue! Leave it open for the moment. I think that it's possible to fix it within this plugin. I'll look into it in the next days.

**Comment by Legion2** [comment]
I'm facing the same issue and I think even though this problem originates from gradle, it must be fixed here, because custom script templates can be used:
https://github.com/beryx/badass-runtime-plugin/blob/d8c200d62c2f8269abab8663a3c1c0e1192cada2/src/main/resources/windowsScriptTemplate.txt#L20

**Comment by siordache** [comment]
Fixed in 1.11.3.

**Comment by Legion2** [comment]
@siordache Thanks

**Comment by TimMcGilly** [comment]
Thank you, that fixed the issue.
