### ISSUE TITLE
Windows: starting app from batch file fails due to JAVA_EXE quoting if 'noConsole' launcher is enabled

### ISSUE THREAD

**Issue by llongi** [beryx/badass-runtime-plugin#68]
Hello, I'm trying out the new feature of having the 'noConsole' flag for the launcher on Windows.

The resulting .bat file is unable to start the application, error:

`Windows cannot find 'C:\Program'.`

It clearly breaks on the space in "C:\Program Files", the culprit seems to be line 56 in the template (and resulting batch file) file:

`start "${applicationName}" "%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %${optsEnvironmentVar}% <% if ( appNameSystemProperty ) { %>"-D${appNameSystemProperty}=%APP_BASE_NAME%"<% } %> -classpath %CLASSPATH% ${mainClassName} %CMD_LINE_ARGS%`

the quotes around %JAVA_EXE% are the issue as far as I can tell, simply removing them lets the application start fine again.

**Comment by siordache** [comment]
Thanks for reporting this issue. It's fixed in 1.11.4.

**Comment by llongi** [comment]
Thank you for the great support!
Tested with runtime 1.11.4, works fine, app starts on Windows.
Issue can be closed from my side.

**Comment by siordache** [comment]
Thanks for the feedback!
