### ISSUE TITLE
Windows launch script can give confusing error message about JAVA_HOME

### ISSUE THREAD

**Issue by shollander** [beryx/badass-runtime-plugin#7]
If the windows launch script cannot locate `java.exe` it will give a confusing error message about `JAVA_HOME` not being set.

https://github.com/beryx/badass-runtime-plugin/blob/d283a8d9039f8c7f77fb12df5daa8f988e15cf77/src/main/resources/windowsScriptTemplate.txt#L20-L30

The reason this message is confusing is because `JAVA_HOME` is set in the script and cannot be set by the user.

This error can occur if one tries to execute an image built for unix (that does not contain `java.exe`) on windows.

**Comment by siordache** [comment]
Fixed in release 1.1.6.
