### ISSUE TITLE
Help with packaging a non modular, non fat jar, JavaFX 11 app

### ISSUE THREAD

**Issue by jschlade** [beryx/badass-runtime-plugin#8]
Thank you for developing this plugin. I'm working on a non modular JavaFX 11.0.02  app and was looking at your pacman example as a model for my packaging.

The pacman example is helpful but I want to use this plugin to a build a non fat jar and this example builds a fat jar. I'm still learning gradle so can someone show me what mods you would need to make to use this plugin to build a non modular, non fat jar, JavaFX 11 app?

Thanks again

**Comment by siordache** [comment]
@jschlade I added an [example project](https://github.com/beryx-gist/badass-runtime-example-javafx) that creates a non-modular, non-fat jar, JavaFX 11 application.

Note that you need to provide a [Launcher](https://github.com/beryx-gist/badass-runtime-example-javafx/blob/master/src/main/java/org/example/hellofx/Launcher.java) class that simply calls the main method of your actual application class.
