### ISSUE TITLE
targetPlatform doesn't appear to generate correct platform vm

### ISSUE THREAD

**Issue by jrepko** [beryx/badass-runtime-plugin#9]
I have a runtime block with two targetPlatform lines, one for 'win' and one for 'linux-x64'.
Both resulting zips contain only 'win' DLLs.  the second argument to each is an unzipped VM appropriate for the target platform.   

I'm running on Windows 10, so 'win' is using the gradle java home.

Maybe I'm using it incorrectly.

**Comment by jrepko** [comment]
I'm a bad person.
You definitely have to use the JDK for the targetPlatform.  It doesn't work if you try to use just the Linux JRE for Java 11.
Switching to the Java 11 JDK for Linux works.

**Comment by siordache** [comment]
> I'm a bad person.
🤣
