### ISSUE TITLE
JPackage for chromeos.

### ISSUE THREAD

**Issue by ghost** [beryx/badass-runtime-plugin#95]
How to create a JPackage for chrome os ?

I created a `.deb`  file in linux .

will this file works on chromeos ?

**Comment by siordache** [comment]
As far as I know, you cannot install Java on Chrome OS. However, on a Chromebook with a Debian distribution, your `.deb` file should work.

**Comment by jeevasci** [comment]
I created my `.deb` file in ubuntu os.

Will it works on chrome os ?

**Comment by jeevasci** [comment]
I am used awt in my java app.

Will chrome os supports awt ?
